/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package visao;

/**
 *
 * @author waldy
 */
public class DialogConfirmarExclusao extends javax.swing.JDialog {
    private boolean confirmarExclusao;
    /**
     * Creates new form DialogConfirmarExclusao
     */
    public DialogConfirmarExclusao(java.awt.Frame parent, boolean modal) {
        initComponents();
        setLocationRelativeTo(parent);
    }

    public boolean getConfirmarExclusaoF() {
        return confirmarExclusao;
    }

    public void setConfirmarExclusaoF(boolean confirmarExclusao) {
        this.confirmarExclusao = confirmarExclusao;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabelTitleDialog3 = new javax.swing.JLabel();
        jLabelTitleDialog4 = new javax.swing.JLabel();
        jLabelTitleDialog5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jButtonCalcelar1 = new javax.swing.JButton();
        jButtonExcluir1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(64, 64, 64));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setModal(true);
        setPreferredSize(new java.awt.Dimension(500, 250));
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(64, 64, 64));

        jLabelTitleDialog3.setBackground(new java.awt.Color(64, 64, 64));
        jLabelTitleDialog3.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabelTitleDialog3.setForeground(new java.awt.Color(255, 187, 0));
        jLabelTitleDialog3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelTitleDialog3.setText("Você está prestes a efetuar uma exclusão!");

        jLabelTitleDialog4.setBackground(new java.awt.Color(64, 64, 64));
        jLabelTitleDialog4.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabelTitleDialog4.setForeground(new java.awt.Color(255, 187, 0));
        jLabelTitleDialog4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitleDialog4.setText("Exclusão");

        jLabelTitleDialog5.setBackground(new java.awt.Color(64, 64, 64));
        jLabelTitleDialog5.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabelTitleDialog5.setForeground(new java.awt.Color(255, 187, 0));
        jLabelTitleDialog5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelTitleDialog5.setText("Tem certeza que deseja que deseja excluir esse item?");

        jPanel4.setBackground(new java.awt.Color(64, 64, 64));

        jPanel5.setBackground(new java.awt.Color(64, 64, 64));
        jPanel5.setLayout(new java.awt.GridLayout(1, 0, 30, 0));

        jButtonCalcelar1.setBackground(new java.awt.Color(156, 156, 156));
        jButtonCalcelar1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jButtonCalcelar1.setForeground(new java.awt.Color(64, 64, 64));
        jButtonCalcelar1.setText("Cancelar");
        jButtonCalcelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalcelar1ActionPerformed(evt);
            }
        });
        jPanel5.add(jButtonCalcelar1);

        jButtonExcluir1.setBackground(new java.awt.Color(156, 156, 156));
        jButtonExcluir1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jButtonExcluir1.setForeground(new java.awt.Color(64, 64, 64));
        jButtonExcluir1.setText("Excluir");
        jButtonExcluir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluir1ActionPerformed(evt);
            }
        });
        jPanel5.add(jButtonExcluir1);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTitleDialog5)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabelTitleDialog3)))
                .addGap(25, 25, 25))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabelTitleDialog4, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitleDialog4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelTitleDialog5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelTitleDialog3)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCalcelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalcelar1ActionPerformed
        // TODO add your handling code here:
        setConfirmarExclusaoF(false);
        this.dispose();
    }//GEN-LAST:event_jButtonCalcelar1ActionPerformed

    private void jButtonExcluir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluir1ActionPerformed
        // TODO add your handling code here:
        setConfirmarExclusaoF(true);
        this.dispose();
    }//GEN-LAST:event_jButtonExcluir1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogConfirmarExclusao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogConfirmarExclusao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogConfirmarExclusao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogConfirmarExclusao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogConfirmarExclusao dialog = new DialogConfirmarExclusao(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCalcelar1;
    private javax.swing.JButton jButtonExcluir1;
    private javax.swing.JLabel jLabelTitleDialog3;
    private javax.swing.JLabel jLabelTitleDialog4;
    private javax.swing.JLabel jLabelTitleDialog5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
}
